window.MATCH = {
 "id": 14566893,
 "date": "2025-10-21",
 "tournament": "UEFA Champions League",
 "season": "UEFA Champions League 25/26",
 "round": 3,
 "home": {
  "name": "PSV Eindhoven",
  "id": 2952,
  "score": 6,
  "crest": "crests/2952.png"
 },
 "away": {
  "name": "Napoli",
  "id": 2714,
  "score": 2,
  "crest": "crests/2714.webp"
 },
 "half_time": {
  "home": 2,
  "away": 1
 },
 "venue": {
  "name": "Philips Stadion",
  "city": "Eindhoven",
  "id": 726
 },
 "attendance": 34700,
 "referee": {
  "name": "Daniel Siebert",
  "id": 67092,
  "country": "Germany"
 },
 "goals": [
  {
   "player": "Scott McTominay",
   "player_id": 879346,
   "team": "Napoli",
   "minute": 31,
   "added_time": null,
   "assist": "Leonardo Spinazzola",
   "assist_id": 148899,
   "type": "regular"
  },
  {
   "player": "Alessandro Buongiorno",
   "player_id": 870263,
   "team": "PSV Eindhoven",
   "minute": 35,
   "added_time": null,
   "assist": null,
   "assist_id": null,
   "type": "ownGoal"
  },
  {
   "player": "Ismael Saibari",
   "player_id": 1063767,
   "team": "PSV Eindhoven",
   "minute": 38,
   "added_time": null,
   "assist": "Guus Til",
   "assist_id": 845798,
   "type": "regular"
  },
  {
   "player": "Dennis Man",
   "player_id": 812145,
   "team": "PSV Eindhoven",
   "minute": 54,
   "added_time": null,
   "assist": "Mauro Júnior",
   "assist_id": 893499,
   "type": "regular"
  },
  {
   "player": "Dennis Man",
   "player_id": 812145,
   "team": "PSV Eindhoven",
   "minute": 80,
   "added_time": null,
   "assist": "Joey Veerman",
   "assist_id": 850816,
   "type": "regular"
  },
  {
   "player": "Scott McTominay",
   "player_id": 879346,
   "team": "Napoli",
   "minute": 85,
   "added_time": null,
   "assist": "David Neres",
   "assist_id": 850993,
   "type": "regular"
  },
  {
   "player": "Ricardo Pepi",
   "player_id": 986395,
   "team": "PSV Eindhoven",
   "minute": 86,
   "added_time": null,
   "assist": "Couhaib Driouech",
   "assist_id": 1047395,
   "type": "regular"
  },
  {
   "player": "Couhaib Driouech",
   "player_id": 1047395,
   "team": "PSV Eindhoven",
   "minute": 89,
   "added_time": null,
   "assist": "Ricardo Pepi",
   "assist_id": 986395,
   "type": "regular"
  }
 ],
 "lineup": {
  "PSV Eindhoven": [
   {
    "name": "M. Kovář",
    "id": 927366,
    "position": "G",
    "country": "cz",
    "minutes": 90,
    "rating": 5.7,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 19
   },
   {
    "name": "M. Júnior",
    "id": 893499,
    "position": "D",
    "country": "br",
    "minutes": 90,
    "rating": 7.8,
    "goals": 0,
    "assists": 1,
    "starter": true,
    "seen": 60
   },
   {
    "name": "R. Flamingo",
    "id": 1046960,
    "position": "D",
    "country": "nl",
    "minutes": 90,
    "rating": 6.6,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 41
   },
   {
    "name": "A. Salah-Eddine",
    "id": 961684,
    "position": "D",
    "country": "ma",
    "minutes": 84,
    "rating": 6.3,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 17
   },
   {
    "name": "Y. Gasiorowski",
    "id": 1184317,
    "position": "D",
    "country": "es",
    "minutes": 45,
    "rating": 6.4,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 18
   },
   {
    "name": "J. Veerman",
    "id": 850816,
    "position": "M",
    "country": "nl",
    "minutes": 90,
    "rating": 7.3,
    "goals": 0,
    "assists": 1,
    "starter": true,
    "seen": 91
   },
   {
    "name": "J. Schouten",
    "id": 844234,
    "position": "M",
    "country": "nl",
    "minutes": 90,
    "rating": 6.9,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 52
   },
   {
    "name": "D. Man",
    "id": 812145,
    "position": "M",
    "country": "ro",
    "minutes": 90,
    "rating": 8.5,
    "goals": 2,
    "assists": 0,
    "starter": true,
    "seen": 17
   },
   {
    "name": "I. Saibari",
    "id": 1063767,
    "position": "M",
    "country": "ma",
    "minutes": 88,
    "rating": 8,
    "goals": 1,
    "assists": 0,
    "starter": true,
    "seen": 79
   },
   {
    "name": "G. Til",
    "id": 845798,
    "position": "M",
    "country": "nl",
    "minutes": 84,
    "rating": 6.7,
    "goals": 0,
    "assists": 1,
    "starter": true,
    "seen": 89
   },
   {
    "name": "I. Perišić",
    "id": 38710,
    "position": "M",
    "country": "hr",
    "minutes": 84,
    "rating": 7,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 34
   },
   {
    "name": "N. Schiks",
    "id": 1134720,
    "position": "G",
    "country": "nl",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 47
   },
   {
    "name": "N. Olij",
    "id": 227192,
    "position": "G",
    "country": "nl",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 17
   },
   {
    "name": "A. Obispo",
    "id": 825838,
    "position": "D",
    "country": "cw",
    "minutes": 45,
    "rating": 6.6,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 78
   },
   {
    "name": "S. Dest",
    "id": 906021,
    "position": "D",
    "country": "us",
    "minutes": 11,
    "rating": 6.5,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 42
   },
   {
    "name": "A. Nagalo",
    "id": 1108094,
    "position": "D",
    "country": "bf",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 25
   },
   {
    "name": "P. Wanner",
    "id": 1146018,
    "position": "M",
    "country": "at",
    "minutes": 2,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 17
   },
   {
    "name": "R. Pepi",
    "id": 986395,
    "position": "F",
    "country": "us",
    "minutes": 11,
    "rating": 7.4,
    "goals": 1,
    "assists": 1,
    "starter": false,
    "seen": 54
   },
   {
    "name": "C. Driouech",
    "id": 1047395,
    "position": "F",
    "country": "ma",
    "minutes": 11,
    "rating": 8.8,
    "goals": 1,
    "assists": 1,
    "starter": false,
    "seen": 36
   },
   {
    "name": "E. Bajraktarević",
    "id": 1136110,
    "position": "F",
    "country": "ba",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 26
   },
   {
    "name": "M. Boadu",
    "id": 856744,
    "position": "F",
    "country": "nl",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 10
   }
  ],
  "Napoli": [
   {
    "name": "V. Milinković-Savić",
    "id": 356160,
    "position": "G",
    "country": "rs",
    "minutes": 90,
    "rating": 5.1,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 1
   },
   {
    "name": "G. Di Lorenzo",
    "id": 153257,
    "position": "D",
    "country": "it",
    "minutes": 90,
    "rating": 4.9,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 2
   },
   {
    "name": "A. Buongiorno",
    "id": 870263,
    "position": "D",
    "country": "it",
    "minutes": 90,
    "rating": 4.8,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 2
   },
   {
    "name": "S. Beukema",
    "id": 898815,
    "position": "D",
    "country": "nl",
    "minutes": 57,
    "rating": 5.5,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 3
   },
   {
    "name": "L. Spinazzola",
    "id": 148899,
    "position": "D",
    "country": "it",
    "minutes": 57,
    "rating": 6.1,
    "goals": 0,
    "assists": 1,
    "starter": true,
    "seen": 2
   },
   {
    "name": "F. Anguissa",
    "id": 787941,
    "position": "M",
    "country": "cm",
    "minutes": 90,
    "rating": 6.4,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 1
   },
   {
    "name": "S. McTominay",
    "id": 879346,
    "position": "M",
    "country": "sx",
    "minutes": 90,
    "rating": 8.3,
    "goals": 2,
    "assists": 0,
    "starter": true,
    "seen": 1
   },
   {
    "name": "K. De Bruyne",
    "id": 70996,
    "position": "M",
    "country": "be",
    "minutes": 84,
    "rating": 6.7,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 1
   },
   {
    "name": "B. Gilmour",
    "id": 907668,
    "position": "M",
    "country": "sx",
    "minutes": 58,
    "rating": 6.3,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 1
   },
   {
    "name": "L. Lucca",
    "id": 962364,
    "position": "F",
    "country": "it",
    "minutes": 76,
    "rating": 5.7,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 3
   },
   {
    "name": "M. Politano",
    "id": 235672,
    "position": "F",
    "country": "it",
    "minutes": 73,
    "rating": 6.3,
    "goals": 0,
    "assists": 0,
    "starter": true,
    "seen": 1
   },
   {
    "name": "A. Meret",
    "id": 592794,
    "position": "G",
    "country": "it",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 2
   },
   {
    "name": "M. Ferrante",
    "id": 1940256,
    "position": "G",
    "country": "it",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 1
   },
   {
    "name": "M. Gutiérrez",
    "id": 908716,
    "position": "D",
    "country": "es",
    "minutes": 33,
    "rating": 5.8,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 4
   },
   {
    "name": "Juan Jesus",
    "id": 108484,
    "position": "D",
    "country": "br",
    "minutes": 33,
    "rating": 6,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 1
   },
   {
    "name": "M. Olivera",
    "id": 805078,
    "position": "D",
    "country": "uy",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 1
   },
   {
    "name": "E. Elmas",
    "id": 838232,
    "position": "M",
    "country": "mk",
    "minutes": 11,
    "rating": 6.4,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 1
   },
   {
    "name": "N. Lang",
    "id": 875136,
    "position": "F",
    "country": "nl",
    "minutes": 32,
    "rating": 6.8,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 31
   },
   {
    "name": "D. Neres",
    "id": 850993,
    "position": "F",
    "country": "br",
    "minutes": 17,
    "rating": 7.4,
    "goals": 0,
    "assists": 1,
    "starter": false,
    "seen": 4
   },
   {
    "name": "A. Vergara",
    "id": 1069560,
    "position": "F",
    "country": "it",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 1
   },
   {
    "name": "G. Ambrosino",
    "id": 1163083,
    "position": "F",
    "country": "it",
    "minutes": 0,
    "rating": null,
    "goals": 0,
    "assists": 0,
    "starter": false,
    "seen": 1
   }
  ]
 },
 "context": {
  "venue_visit": 84,
  "venue_total": 94,
  "venue_first": "2018-10-24",
  "club_match": 112,
  "tournament_match": 22,
  "match_nr": 166,
  "total_matches": 180
 }
};
